# Generated by Django 3.2.5 on 2021-07-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bid_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='imgage',
            new_name='image',
        ),
    ]
