# Generated by Django 3.2.5 on 2021-07-19 21:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comment_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 21, 39, 14, 12500, tzinfo=utc)),
        ),
    ]
