# Generated by Django 3.2.5 on 2021-07-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_comment_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
