# Generated by Django 3.2.5 on 2021-07-19 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_user_watching'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watching',
        ),
    ]
