# Generated by Django 3.2.5 on 2021-07-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_user_watching'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watching',
        ),
        migrations.AddField(
            model_name='user',
            name='watching',
            field=models.ManyToManyField(default=False, related_name='watch', to='auctions.AuctionListing'),
        ),
    ]
