# Generated by Django 3.2.5 on 2021-07-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='start_bid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bid',
            name='value',
            field=models.IntegerField(),
        ),
    ]
